name: Snowflake Pipeline Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    env:
       REPO_NAME: "SnowflakeTest.public.repo"
       SNOWFLAKE_ACCOUNT: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
       SNOWFLAKE_USER: "${{ secrets.SNOWFLAKE_USER }}"
       SNOWFLAKE_PASSWORD: "${{ secrets.SNOWFLAKE_PASSWORD }}"
       SNOWFLAKE_WAREHOUSE: "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
       SNOWFLAKE_DATABASE: "${{ secrets.SNOWFLAKE_DATABASE }}"

    steps:

      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install snowflake-cli
      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      # Step 3: Fetch repository changes
      - name: Fetch repository changes
        run: |
          snow git fetch "%REPO_NAME%"

      # Step 4: Execute extract.sql
      - name: Execute extract.sql
        run: |
          snow sql execute \
            --account-name "${{ env.SNOWFLAKE_ACCOUNT }}" \
            --username "${{ env.SNOWFLAKE_USER }}" \
            --password "${{ env.SNOWFLAKE_PASSWORD }}" \
            --warehouse "${{ env.SNOWFLAKE_WAREHOUSE }}" \
            --database "${{ env.SNOWFLAKE_DATABASE }}" \
            --file ./extract.sql
